services:
  docker-local-persist-volume-plugin:
    image: cwspear/docker-local-persist-volume-plugin
    volumes:
      - /run/docker/plugins/:/run/docker/plugins/
      - ./.config/:/var/lib/docker/plugin-data/
      - ./.data/:/path/to/where/you/want/data/volume/
