services:
  docker-local-persist-volume-plugin:
    image: cwspear/docker-local-persist-volume-plugin:${lp_volume_version:-latest}
    volumes:
      - /run/docker/plugins/:/run/docker/plugins/
      - ./.config/:/var/lib/docker/plugin-data/
      - ./.data/:/opt/docker/volumes/
